export { default as Home } from './Home'
export { default as Documents } from './Documents'
export { default as Perfomance } from './Perfomance'
export { default as Schedule } from './Schedule'
export { default as Marks } from './Marks'